# This is a basic workflow to help you get started with Actions

name: GIPO FE build

# Controls when the action will run. 
on:
  # Triggers the workflow on push on all branches ignoring main or develop
  pull_request:
    types: [labeled, unlabeled]
    # Trigger the workflow only if anything changes inside the Gipo FE folders

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # add-labels:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: add labels
  #       uses: actions-ecosystem/action-add-labels@v1
  #       if: env.BASE_BRANCH != 'develop' && env.BASE_BRANCH != 'master'
  #       with:
  #         github_token: ${{ github.token }}
  #         labels: Skip-build

  build:
    if: ${{ contains(github.event.*.labels.*.name, 'skip-build') }}
    name: Build project
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run build
      working-directory: src
      run: |
        echo "${github.event.*.labels.*.name}"
        yarn install
        yarn build
